// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebMensajeria.API.Migrations
{
    [DbContext(typeof(WebMensajeriaAPIContext))]
    [Migration("20261001224741_V01")]
    partial class V01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebMensajeria.Modelos.AdjuntoMensaje", b =>
                {
                    b.Property<int>("idAdjunto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_adjunto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idAdjunto"));

                    b.Property<int>("idMensaje")
                        .HasColumnType("integer")
                        .HasColumnName("id_mensaje");

                    b.Property<int>("idTipoAdjunto")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_adjunto");

                    b.Property<string>("urlArchivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_archivo");

                    b.HasKey("idAdjunto");

                    b.HasIndex("idMensaje");

                    b.HasIndex("idTipoAdjunto");

                    b.ToTable("adjuntoMensajes");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.Chat", b =>
                {
                    b.Property<int>("idChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_chat");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idChat"));

                    b.Property<int>("idTipoChat")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_chat");

                    b.HasKey("idChat");

                    b.HasIndex("idTipoChat");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.Contacto", b =>
                {
                    b.Property<int>("idContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_contacto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idContacto"));

                    b.Property<int>("idUsuarioContacto")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_contacto");

                    b.Property<int>("idUsuarioPrincipal")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_principal");

                    b.HasKey("idContacto");

                    b.HasIndex("idUsuarioContacto");

                    b.HasIndex("idUsuarioPrincipal");

                    b.ToTable("contactos");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.DetalleGrupo", b =>
                {
                    b.Property<int>("idDetalleGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_grupo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idDetalleGrupo"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idChat")
                        .HasColumnType("integer")
                        .HasColumnName("Id_chat");

                    b.Property<string>("nombreGrupo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_grupo");

                    b.HasKey("idDetalleGrupo");

                    b.HasIndex("idChat");

                    b.ToTable("detallesGrupos");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.EstadoReceptorMensaje", b =>
                {
                    b.Property<int>("idEstadoReceptor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estado_recpetor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idEstadoReceptor"));

                    b.Property<int>("idMensaje")
                        .HasColumnType("integer")
                        .HasColumnName("id_mensaje");

                    b.Property<int>("idUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_receptor");

                    b.Property<int>("tipoEstado")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_estado");

                    b.HasKey("idEstadoReceptor");

                    b.HasIndex("idMensaje");

                    b.HasIndex("idUsuario");

                    b.HasIndex("tipoEstado");

                    b.ToTable("estadoreceptormesajes");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.Mensaje", b =>
                {
                    b.Property<int>("idMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_mensaje");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idMensaje"));

                    b.Property<DateTime>("fechaEnvio")
                        .HasColumnType("timestamp")
                        .HasColumnName("Fecha_envio");

                    b.Property<int>("idChat")
                        .HasColumnType("integer")
                        .HasColumnName("id_chat");

                    b.Property<int>("idUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_Usuario_remitente");

                    b.Property<string>("mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idMensaje");

                    b.HasIndex("idChat");

                    b.HasIndex("idUsuario");

                    b.ToTable("mensajes");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.ParticipanteChat", b =>
                {
                    b.Property<int>("idParticipante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_participante_chat");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idParticipante"));

                    b.Property<int>("idChat")
                        .HasColumnType("integer")
                        .HasColumnName("id_chat");

                    b.Property<int>("idRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<int>("idUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.HasKey("idParticipante");

                    b.HasIndex("idChat");

                    b.HasIndex("idRol");

                    b.HasIndex("idUsuario");

                    b.ToTable("Participanteschats");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.ReaccionMensaje", b =>
                {
                    b.Property<int>("idReaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_reaccion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idReaccion"));

                    b.Property<int?>("TipoReaccionidTipoReaccion")
                        .HasColumnType("integer");

                    b.Property<int>("idMensaje")
                        .HasColumnType("integer")
                        .HasColumnName("id_mensaje");

                    b.Property<int>("idTipoReaccion")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_reaccion");

                    b.Property<int>("idUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.HasKey("idReaccion");

                    b.HasIndex("TipoReaccionidTipoReaccion");

                    b.HasIndex("idMensaje");

                    b.HasIndex("idUsuario");

                    b.ToTable("ReaccionMensaje");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.RolParticipante", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("nombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombe_rol");

                    b.HasKey("IdRol");

                    b.ToTable("rolparticipantes");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.TipoAdjunto", b =>
                {
                    b.Property<int>("idTipoAdjunto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_adjunto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTipoAdjunto"));

                    b.Property<string>("nombreTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_tipo");

                    b.HasKey("idTipoAdjunto");

                    b.ToTable("tipoAdjuntos");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.TipoChat", b =>
                {
                    b.Property<int>("idTipoChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_chat");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTipoChat"));

                    b.Property<string>("nombreTipoChat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_tipo_chat");

                    b.HasKey("idTipoChat");

                    b.ToTable("tipoChats");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.TipoEstadoMensaje", b =>
                {
                    b.Property<int>("idTipoEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_estado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTipoEstado"));

                    b.Property<string>("tipoEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("idTipoEstado");

                    b.ToTable("tipoestados");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.TipoReaccion", b =>
                {
                    b.Property<int>("idTipoReaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_reaccion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTipoReaccion"));

                    b.Property<string>("simbolo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("idTipoReaccion");

                    b.ToTable("tiporeacciones");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("correoelectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.AdjuntoMensaje", b =>
                {
                    b.HasOne("WebMensajeria.Modelos.Mensaje", "mensajes")
                        .WithMany("adjuntos")
                        .HasForeignKey("idMensaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMensajeria.Modelos.TipoAdjunto", "tiposAdjutnos")
                        .WithMany("adjuntos")
                        .HasForeignKey("idTipoAdjunto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mensajes");

                    b.Navigation("tiposAdjutnos");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.Chat", b =>
                {
                    b.HasOne("WebMensajeria.Modelos.TipoChat", "tipoChat")
                        .WithMany("chats")
                        .HasForeignKey("idTipoChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoChat");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.Contacto", b =>
                {
                    b.HasOne("WebMensajeria.Modelos.Usuario", "usuario_contacto")
                        .WithMany("soyContacto")
                        .HasForeignKey("idUsuarioContacto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMensajeria.Modelos.Usuario", "usuario_principal")
                        .WithMany("misContactos")
                        .HasForeignKey("idUsuarioPrincipal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario_contacto");

                    b.Navigation("usuario_principal");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.DetalleGrupo", b =>
                {
                    b.HasOne("WebMensajeria.Modelos.Chat", "chats")
                        .WithMany()
                        .HasForeignKey("idChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chats");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.EstadoReceptorMensaje", b =>
                {
                    b.HasOne("WebMensajeria.Modelos.Mensaje", "mensajes")
                        .WithMany("estadoReceptorMensajes")
                        .HasForeignKey("idMensaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMensajeria.Modelos.Usuario", "usuarioReceptor")
                        .WithMany("estadoReceptorMensajes")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMensajeria.Modelos.TipoEstadoMensaje", "tipoEstadoMensaje")
                        .WithMany("estadoReceptorMensajes")
                        .HasForeignKey("tipoEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mensajes");

                    b.Navigation("tipoEstadoMensaje");

                    b.Navigation("usuarioReceptor");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.Mensaje", b =>
                {
                    b.HasOne("WebMensajeria.Modelos.Chat", "chats")
                        .WithMany("mensajes")
                        .HasForeignKey("idChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMensajeria.Modelos.Usuario", "usuarioRemitente")
                        .WithMany("mensajesEnviados")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chats");

                    b.Navigation("usuarioRemitente");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.ParticipanteChat", b =>
                {
                    b.HasOne("WebMensajeria.Modelos.Chat", "chats")
                        .WithMany("participantesChats")
                        .HasForeignKey("idChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMensajeria.Modelos.RolParticipante", "roles")
                        .WithMany("participantesChats")
                        .HasForeignKey("idRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMensajeria.Modelos.Usuario", "usuarios")
                        .WithMany("participantesChats")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chats");

                    b.Navigation("roles");

                    b.Navigation("usuarios");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.ReaccionMensaje", b =>
                {
                    b.HasOne("WebMensajeria.Modelos.TipoReaccion", "TipoReaccion")
                        .WithMany("reaccionMensajes")
                        .HasForeignKey("TipoReaccionidTipoReaccion");

                    b.HasOne("WebMensajeria.Modelos.Mensaje", "mensajes")
                        .WithMany("reaccionMensajes")
                        .HasForeignKey("idMensaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMensajeria.Modelos.Usuario", "usuario")
                        .WithMany("reaccionMensajes")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoReaccion");

                    b.Navigation("mensajes");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.Chat", b =>
                {
                    b.Navigation("mensajes");

                    b.Navigation("participantesChats");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.Mensaje", b =>
                {
                    b.Navigation("adjuntos");

                    b.Navigation("estadoReceptorMensajes");

                    b.Navigation("reaccionMensajes");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.RolParticipante", b =>
                {
                    b.Navigation("participantesChats");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.TipoAdjunto", b =>
                {
                    b.Navigation("adjuntos");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.TipoChat", b =>
                {
                    b.Navigation("chats");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.TipoEstadoMensaje", b =>
                {
                    b.Navigation("estadoReceptorMensajes");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.TipoReaccion", b =>
                {
                    b.Navigation("reaccionMensajes");
                });

            modelBuilder.Entity("WebMensajeria.Modelos.Usuario", b =>
                {
                    b.Navigation("estadoReceptorMensajes");

                    b.Navigation("mensajesEnviados");

                    b.Navigation("misContactos");

                    b.Navigation("participantesChats");

                    b.Navigation("reaccionMensajes");

                    b.Navigation("soyContacto");
                });
#pragma warning restore 612, 618
        }
    }
}
